import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import StoreProvider from "@/components/providers/store-provider";
import Sidebar from "@/components/common/sidebar";
import Navbar from "@/components/common/navbar";
import CommonScrollArea from "@/components/common/common-scroll-area";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <main className="flex">
              <Sidebar />

              <div className="flex-1 flex-col min-h-screen">
                <Navbar />

                <CommonScrollArea>{children}</CommonScrollArea>
              </div>
            </main>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
