export const noticesData = [
  {
    id: "1",
    title: "Office closed on Friday for maintenance.",
    type: "General / Company-Wide",
    department: "All Department",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "2",
    title: "Eid al-Fitr holiday schedule.",
    type: "Holiday & Event",
    department: "Finance",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "3",
    title: "Updated code of conduct policy",
    type: "HR & Policy Update",
    department: "Sales Team",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "4",
    title: "Payroll for October will be processed on 28th",
    type: "Finance & Payroll",
    department: "Web Team",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "5",
    title: "System update scheduled for 30 Oct (9:00–11:00 PM)",
    type: "IT / System Maintenance",
    department: "Database Team",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "6",
    title: "Design team sprint review moved to Tuesday.",
    type: "Department / Team",
    department: "Admin",
    date: "15-Jun-2025",
    status: "Published",
  },
  {
    id: "7",
    title: "Unauthorized absence recorded on 18 Oct 2025",
    type: "Warning / Disciplinary",
    department: "Individual",
    date: "15-Jun-2025",
    status: "Unpublished",
  },
  {
    id: "8",
    title: "Office closed today due to severe weather",
    type: "Emergency / Urgent",
    department: "HR",
    date: "15-Jun-2025",
    status: "Draft",
  },
  {
    id: "9",
    title: "Annual performance review cycle starts from 1 July",
    type: "HR & Performance",
    department: "All Department",
    date: "20-Jun-2025",
    status: "Published",
  },
  {
    id: "10",
    title: "New employee onboarding session this Monday",
    type: "Training / Onboarding",
    department: "HR",
    date: "21-Jun-2025",
    status: "Published",
  },
  {
    id: "11",
    title: "Cybersecurity awareness training mandatory for all staff",
    type: "IT / Security",
    department: "All Department",
    date: "22-Jun-2025",
    status: "Published",
  },
  {
    id: "12",
    title: "Sales target review meeting postponed",
    type: "Department / Team",
    department: "Sales Team",
    date: "23-Jun-2025",
    status: "Published",
  },
  {
    id: "13",
    title: "New health insurance policy effective from July",
    type: "Benefits & Compensation",
    department: "HR",
    date: "24-Jun-2025",
    status: "Published",
  },
  {
    id: "14",
    title: "Server downtime expected on Sunday midnight",
    type: "IT / System Maintenance",
    department: "Web Team",
    date: "25-Jun-2025",
    status: "Published",
  },
  {
    id: "15",
    title: "Reminder: Submit travel expense claims by month-end",
    type: "Finance & Payroll",
    department: "All Department",
    date: "26-Jun-2025",
    status: "Published",
  },
  {
    id: "16",
    title: "Marketing campaign kickoff meeting announcement",
    type: "Department / Team",
    department: "Marketing Team",
    date: "27-Jun-2025",
    status: "Draft",
  },
  {
    id: "17",
    title: "Updated remote work policy guidelines",
    type: "HR & Policy Update",
    department: "All Department",
    date: "28-Jun-2025",
    status: "Published",
  },
  {
    id: "18",
    title: "Disciplinary hearing scheduled for policy violation",
    type: "Warning / Disciplinary",
    department: "Individual",
    date: "29-Jun-2025",
    status: "Unpublished",
  },
  {
    id: "19",
    title: "Quarterly town hall meeting with CEO",
    type: "General / Company-Wide",
    department: "All Department",
    date: "30-Jun-2025",
    status: "Published",
  },
  {
    id: "20",
    title: "Office reopening notice after renovation",
    type: "General / Company-Wide",
    department: "Admin",
    date: "01-Jul-2025",
    status: "Published",
  },
];
